### ISSUE TITLE
NameError: name 'vs' is not defined

### ISSUE THREAD

**Issue by Jorigorn** [Bachfischer/german2vec#1]
Have set up all the environments, in 
 src/sb-10k-use_pretrained_language_model-fixed_LR.ipynb
and 
src/sb-10k-use_pretrained_language_model.ipynb

both showed :

---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-11-57a132f55034> in <module>()
      2 drops = np.array([0.25, 0.1, 0.2, 0.02, 0.15])*0.1 # if you're overfitting, increase this. Underfitting? decrease this.
      3 
----> 4 md = LanguageModelData(PATH, 1, vs, trn_dl, val_dl, bs=bs, bptt=bptt)
      5 learner= md.get_model(opt_fn, em_sz, nh, nl, 
      6     dropouti=drops[0], dropout=drops[1], wdrop=drops[2], dropoute=drops[3], dropouth=drops[4])

NameError: name 'vs' is not defined

**Comment by Bachfischer** [comment]
Hi,

the code from the "Extract Embeddings from Language Model" section can only be run once the language model has been loaded at least once (I was mainly just playing around a bit when I added that section).

To successfully load the classifier, please skip this section and run the notebook from "Classifier Tokens" onwards!
